apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatbot-test-app-22 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=chatbot-test-app-22
    backstage.io/kubernetes-id: chatbot-test-app-22 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: chatbot-test-app-22
    quay.io/repository-slug: mvaldron-rhdh/rhtap-go-app-2
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:default/michael-valdron 
  lifecycle: experimental
 